### ISSUE TITLE
Watchdog instance

### ISSUE THREAD

**Issue by Larswad** [DoubleAJ/watchdog-device#1]
There can be multiple watchdog instances in a system, e.g. /dev/watchdog0, /dev/watchdog1 and so on.

As of now the watchdog path is hardcoded to /dev/watchdog which may not always be desired.

It would be nice with either an additional Open-function where the instance number is given,
or that the instance must always be given.

Best Regards

**Comment by DoubleAJ** [comment]
Hi Lars, 
It is a good idea. It would be useful to be able to activate more than just the default watchdog.
The default behaviour shall remain the same (i.e. _/dev/watchdog_), but a new function would allow the creation of an instance by explicitly indicating the ID of the file to open (0, 1 .. N).
I will take a look into it.

Thank you for your feedback!

**Comment by DoubleAJ** [comment]
The changes were merged to the main branch. 
I will start preparing a new release soon.

**Comment by Larswad** [comment]
Deep thanks for the very quick addition of this api enhancement. Deeply greatful since it will help our project move forward without making our own crate for watchdog handling.

**Comment by DoubleAJ** [comment]
The new version was released. Let me know if there is any issue with it.
I'm glad to have been able to help you guys!
